name: Doxygen

on:
  # Manual workflow dispatch
  workflow_dispatch:

# In that case do the job 'make_and_deploy_doxygen'
jobs:
  make_and_deploy_doxygen:
    runs-on: ubuntu-latest
    # which needs the following steps to be executed:
    steps:
      # 1. Checkout current branch of GitHub repository.
      - name: Checkout current branch
        uses: actions/checkout@v4
      # 2. Install doxygen and its auxiliary components.
      - name: Install doxygen
        run: sudo apt-get update; sudo apt-get install -y doxygen
      # 3. Create the doxygen pages.
      - name: Create the doxygen
        run: |
          git clone https://github.com/Meta-Real/MetaReal.git
          cd MetaReal
          doxygen ./Doxyfile
      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./MetaReal/docs/html/
          publish_branch: main
